version: "3.8"

services:
  open-webui:
    build: .
    container_name: open-webui
    ports:
      - "3000:8080"
    volumes:
      - ollama:/root/.ollama
      - open-webui:/app/backend/data
    restart: always

volumes:
  ollama:
  open-webui:
